version: "3.9"

services:
  website-generator:
    build: .
    container_name: website_generator_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./sites:/app/sites

    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
